language: bash
sudo: required
dist: trusty
env:
- OS=debian ARCH=amd64 DIST=stretch
- OS=debian ARCH=i386 DIST=stretch
- OS=debian ARCH=armhf DIST=stretch
- OS=raspbian ARCH=armhf DIST=stretch
- OS=debian ARCH=armel DIST=stretch
cache:
  directories:
  - "$HOME/cache"
before_install:
- sudo apt-add-repository "deb http://archive.ev3dev.org/ubuntu trusty main"
- sudo cp .travis/ev3dev-archive-keyring.gpg /etc/apt/trusted.gpg.d/
- sudo apt-get update
- sudo apt-get install --yes pbuilder-ev3dev dh-systemd
before_script:
- pbuilder-ev3dev base
- git checkout -B ev3dev-stretch
script:
- pbuilder-ev3dev build
