language: bash
sudo: required
dist: bionic
env:
- OS=debian ARCH=amd64 DIST=bullseye
- OS=debian ARCH=armel DIST=bullseye QEMU_USER_STATIC=qemu-user-static
cache:
  directories:
  - "$HOME/cache"
before_install:
- sudo apt-add-repository -y ppa:ev3dev/tools
- sudo apt-get update
- sudo apt-get install --yes debhelper pbuilder-ev3dev $QEMU_USER_STATIC
before_script:
- pbuilder-ev3dev base
- git checkout -B ev3dev-bullseye
script:
- pbuilder-ev3dev build
